
package com.isap.core;

import java.util.List;
import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.isap.cloudmanager.requests.xsd.AddOpenstackFloatingIpReq;
import com.isap.cloudmanager.requests.xsd.AllocateOpenstackFloatingIpReq;
import com.isap.cloudmanager.requests.xsd.DeallocateOpenstackFloatingIpReq;
import com.isap.cloudmanager.requests.xsd.FreeFloatingIPsReq;
import com.isap.cloudmanager.requests.xsd.GetOpenstackFlavorDetailsReq;
import com.isap.cloudmanager.requests.xsd.GetOpenstackImageDetailsReq;
import com.isap.cloudmanager.requests.xsd.GetOpenstackSecurityGroupDetailsReq;
import com.isap.cloudmanager.requests.xsd.ListOpenstackFlavorsReq;
import com.isap.cloudmanager.requests.xsd.ListOpenstackImagesReq;
import com.isap.cloudmanager.requests.xsd.ListOpenstackKeypairsReq;
import com.isap.cloudmanager.requests.xsd.ListOpenstackNetworksReq;
import com.isap.cloudmanager.requests.xsd.ListOpenstackSecurityGroupsReq;
import com.isap.cloudmanager.requests.xsd.OpenstackBasicReq;
import com.isap.cloudmanager.requests.xsd.RemoveOpenstackFloatingIpReq;
import com.isap.cloudmanager.responses.xsd.AddOpenstackFloatingIpResp;
import com.isap.cloudmanager.responses.xsd.AllocateOpenstackFloatingIpResp;
import com.isap.cloudmanager.responses.xsd.GetOpenstackFlavorResp;
import com.isap.cloudmanager.responses.xsd.GetOpenstackFloatingIpResp;
import com.isap.cloudmanager.responses.xsd.GetOpenstackImageDetailsResp;
import com.isap.cloudmanager.responses.xsd.OpenstackBasicResp;
import com.isap.cloudmanager.responses.xsd.RemoveOpenstackFloatingIpResp;
import com.isap.core.requests.xsd.CreateOpenstackKeypairReq;
import com.isap.core.requests.xsd.CreateOpenstacktenantReq;
import com.isap.core.requests.xsd.GetIsapCloudAuthenticationRequest;
import com.isap.core.requests.xsd.GetIsapLaunchInstanceReq;
import com.isap.core.requests.xsd.GetIsapinstanceDetailsReq;
import com.isap.core.requests.xsd.GetOpenstackHypervisorDetailsReq;
import com.isap.core.requests.xsd.GetOpenstackQuotaReq;
import com.isap.core.requests.xsd.TerminateOpensInstanceReq;
import com.isap.core.responses.xsd.CreateOpenstackTenantResp;
import com.isap.core.responses.xsd.CreateOpenstackkeypairResp;
import com.isap.core.responses.xsd.GetIsapCloudAuthenticationResponse;
import com.isap.core.responses.xsd.GetIsapInstanceDetailsResp;
import com.isap.core.responses.xsd.GetIsapLaunchInstanceResp;
import com.isap.core.responses.xsd.GetOpenstackHypervisorDetailsResp;
import com.isap.core.responses.xsd.GetOpenstackQuotaResp;
import com.isap.core.responses.xsd.GetOpenstackSecurityGroupDetailsResp;
import com.isap.core.responses.xsd.ListOpenstackFlavorsResp;
import com.isap.core.responses.xsd.ListOpenstackImagesResp;
import com.isap.core.responses.xsd.ListOpenstackKeypairsResp;
import com.isap.core.responses.xsd.ListOpenstackNetworksResp;
import com.isap.core.responses.xsd.ListOpenstackSecurityGroupsResp;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IsapCoreWebservicesPortType", targetNamespace = "http://core.isap.com")
@XmlSeeAlso({
    com.isap.cloudmanager.requests.xsd.ObjectFactory.class,
    com.isap.cloudmanager.responses.xsd.ObjectFactory.class,
    com.isap.core.ObjectFactory.class,
    com.isap.core.requests.xsd.ObjectFactory.class,
    com.isap.core.responses.xsd.ObjectFactory.class
})
public interface IsapCoreWebservicesPortType {


    /**
     * 
     * @param gosgr
     * @return
     *     returns com.isap.core.responses.xsd.GetOpenstackSecurityGroupDetailsResp
     */
    @WebMethod(operationName = "GetOpenstackSecurityGroupDetails", action = "urn:GetOpenstackSecurityGroupDetails")
    @WebResult(targetNamespace = "http://core.isap.com")
    @RequestWrapper(localName = "GetOpenstackSecurityGroupDetails", targetNamespace = "http://core.isap.com", className = "com.isap.core.GetOpenstackSecurityGroupDetails")
    @ResponseWrapper(localName = "GetOpenstackSecurityGroupDetailsResponse", targetNamespace = "http://core.isap.com", className = "com.isap.core.GetOpenstackSecurityGroupDetailsResponse")
    public GetOpenstackSecurityGroupDetailsResp getOpenstackSecurityGroupDetails(
        @WebParam(name = "gosgr", targetNamespace = "http://core.isap.com")
        GetOpenstackSecurityGroupDetailsReq gosgr);

    /**
     * 
     * @param request
     * @return
     *     returns com.isap.cloudmanager.responses.xsd.OpenstackBasicResp
     */
    @WebMethod(action = "urn:deallocateOpenstackFloatingIp")
    @WebResult(targetNamespace = "http://core.isap.com")
    @RequestWrapper(localName = "deallocateOpenstackFloatingIp", targetNamespace = "http://core.isap.com", className = "com.isap.core.DeallocateOpenstackFloatingIp")
    @ResponseWrapper(localName = "deallocateOpenstackFloatingIpResponse", targetNamespace = "http://core.isap.com", className = "com.isap.core.DeallocateOpenstackFloatingIpResponse")
    public OpenstackBasicResp deallocateOpenstackFloatingIp(
        @WebParam(name = "request", targetNamespace = "http://core.isap.com")
        DeallocateOpenstackFloatingIpReq request);

    /**
     * 
     * @param afip
     * @return
     *     returns com.isap.cloudmanager.responses.xsd.AddOpenstackFloatingIpResp
     */
    @WebMethod(action = "urn:addOpenstackFloatingIp")
    @WebResult(targetNamespace = "http://core.isap.com")
    @RequestWrapper(localName = "addOpenstackFloatingIp", targetNamespace = "http://core.isap.com", className = "com.isap.core.AddOpenstackFloatingIp")
    @ResponseWrapper(localName = "addOpenstackFloatingIpResponse", targetNamespace = "http://core.isap.com", className = "com.isap.core.AddOpenstackFloatingIpResponse")
    public AddOpenstackFloatingIpResp addOpenstackFloatingIp(
        @WebParam(name = "afip", targetNamespace = "http://core.isap.com")
        AddOpenstackFloatingIpReq afip);

    /**
     * 
     * @param gilir
     * @return
     *     returns com.isap.core.responses.xsd.GetIsapLaunchInstanceResp
     */
    @WebMethod(operationName = "GetIsapLaunchinstance", action = "urn:GetIsapLaunchinstance")
    @WebResult(targetNamespace = "http://core.isap.com")
    @RequestWrapper(localName = "GetIsapLaunchinstance", targetNamespace = "http://core.isap.com", className = "com.isap.core.GetIsapLaunchinstance")
    @ResponseWrapper(localName = "GetIsapLaunchinstanceResponse", targetNamespace = "http://core.isap.com", className = "com.isap.core.GetIsapLaunchinstanceResponse")
    public GetIsapLaunchInstanceResp getIsapLaunchinstance(
        @WebParam(name = "gilir", targetNamespace = "http://core.isap.com")
        GetIsapLaunchInstanceReq gilir);

    /**
     * 
     * @param req
     * @return
     *     returns com.isap.cloudmanager.responses.xsd.AllocateOpenstackFloatingIpResp
     */
    @WebMethod(action = "urn:allocateOpenstackFloatingIp")
    @WebResult(targetNamespace = "http://core.isap.com")
    @RequestWrapper(localName = "allocateOpenstackFloatingIp", targetNamespace = "http://core.isap.com", className = "com.isap.core.AllocateOpenstackFloatingIp")
    @ResponseWrapper(localName = "allocateOpenstackFloatingIpResponse", targetNamespace = "http://core.isap.com", className = "com.isap.core.AllocateOpenstackFloatingIpResponse")
    public AllocateOpenstackFloatingIpResp allocateOpenstackFloatingIp(
        @WebParam(name = "req", targetNamespace = "http://core.isap.com")
        AllocateOpenstackFloatingIpReq req);

    /**
     * 
     * @param losgr
     * @return
     *     returns com.isap.core.responses.xsd.ListOpenstackSecurityGroupsResp
     */
    @WebMethod(operationName = "ListOpenstackSecurityGroups", action = "urn:ListOpenstackSecurityGroups")
    @WebResult(targetNamespace = "http://core.isap.com")
    @RequestWrapper(localName = "ListOpenstackSecurityGroups", targetNamespace = "http://core.isap.com", className = "com.isap.core.ListOpenstackSecurityGroups")
    @ResponseWrapper(localName = "ListOpenstackSecurityGroupsResponse", targetNamespace = "http://core.isap.com", className = "com.isap.core.ListOpenstackSecurityGroupsResponse")
    public ListOpenstackSecurityGroupsResp listOpenstackSecurityGroups(
        @WebParam(name = "losgr", targetNamespace = "http://core.isap.com")
        ListOpenstackSecurityGroupsReq losgr);

    /**
     * 
     * @param args
     */
    @WebMethod(action = "urn:main")
    @Oneway
    @RequestWrapper(localName = "main", targetNamespace = "http://core.isap.com", className = "com.isap.core.Main")
    public void main(
        @WebParam(name = "args", targetNamespace = "http://core.isap.com")
        List<String> args);

    /**
     * 
     * @param rfip
     * @return
     *     returns com.isap.cloudmanager.responses.xsd.RemoveOpenstackFloatingIpResp
     */
    @WebMethod(operationName = "RemoveOpenstackFloatingIpResp", action = "urn:RemoveOpenstackFloatingIpResp")
    @WebResult(targetNamespace = "http://core.isap.com")
    @RequestWrapper(localName = "RemoveOpenstackFloatingIpResp", targetNamespace = "http://core.isap.com", className = "com.isap.core.RemoveOpenstackFloatingIpResp")
    @ResponseWrapper(localName = "RemoveOpenstackFloatingIpRespResponse", targetNamespace = "http://core.isap.com", className = "com.isap.core.RemoveOpenstackFloatingIpRespResponse")
    public RemoveOpenstackFloatingIpResp removeOpenstackFloatingIpResp(
        @WebParam(name = "rfip", targetNamespace = "http://core.isap.com")
        RemoveOpenstackFloatingIpReq rfip);

    /**
     * 
     * @param goidr
     * @return
     *     returns com.isap.cloudmanager.responses.xsd.GetOpenstackImageDetailsResp
     */
    @WebMethod(operationName = "GetOpenstackImageDetails", action = "urn:GetOpenstackImageDetails")
    @WebResult(targetNamespace = "http://core.isap.com")
    @RequestWrapper(localName = "GetOpenstackImageDetails", targetNamespace = "http://core.isap.com", className = "com.isap.core.GetOpenstackImageDetails")
    @ResponseWrapper(localName = "GetOpenstackImageDetailsResponse", targetNamespace = "http://core.isap.com", className = "com.isap.core.GetOpenstackImageDetailsResponse")
    public GetOpenstackImageDetailsResp getOpenstackImageDetails(
        @WebParam(name = "goidr", targetNamespace = "http://core.isap.com")
        GetOpenstackImageDetailsReq goidr);

    /**
     * 
     * @param lonr
     * @return
     *     returns com.isap.core.responses.xsd.ListOpenstackNetworksResp
     */
    @WebMethod(operationName = "ListOpenstackNetworks", action = "urn:ListOpenstackNetworks")
    @WebResult(targetNamespace = "http://core.isap.com")
    @RequestWrapper(localName = "ListOpenstackNetworks", targetNamespace = "http://core.isap.com", className = "com.isap.core.ListOpenstackNetworks")
    @ResponseWrapper(localName = "ListOpenstackNetworksResponse", targetNamespace = "http://core.isap.com", className = "com.isap.core.ListOpenstackNetworksResponse")
    public ListOpenstackNetworksResp listOpenstackNetworks(
        @WebParam(name = "lonr", targetNamespace = "http://core.isap.com")
        ListOpenstackNetworksReq lonr);

    /**
     * 
     * @param ffip
     * @return
     *     returns com.isap.cloudmanager.responses.xsd.GetOpenstackFloatingIpResp
     */
    @WebMethod(action = "urn:freeFloatingIPs")
    @WebResult(targetNamespace = "http://core.isap.com")
    @RequestWrapper(localName = "freeFloatingIPs", targetNamespace = "http://core.isap.com", className = "com.isap.core.FreeFloatingIPs")
    @ResponseWrapper(localName = "freeFloatingIPsResponse", targetNamespace = "http://core.isap.com", className = "com.isap.core.FreeFloatingIPsResponse")
    public GetOpenstackFloatingIpResp freeFloatingIPs(
        @WebParam(name = "ffip", targetNamespace = "http://core.isap.com")
        FreeFloatingIPsReq ffip);

    /**
     * 
     * @param loir
     * @return
     *     returns com.isap.core.responses.xsd.ListOpenstackImagesResp
     */
    @WebMethod(operationName = "ListOpenstackImages", action = "urn:ListOpenstackImages")
    @WebResult(targetNamespace = "http://core.isap.com")
    @RequestWrapper(localName = "ListOpenstackImages", targetNamespace = "http://core.isap.com", className = "com.isap.core.ListOpenstackImages")
    @ResponseWrapper(localName = "ListOpenstackImagesResponse", targetNamespace = "http://core.isap.com", className = "com.isap.core.ListOpenstackImagesResponse")
    public ListOpenstackImagesResp listOpenstackImages(
        @WebParam(name = "loir", targetNamespace = "http://core.isap.com")
        ListOpenstackImagesReq loir);

    /**
     * 
     * @param vmCustomId
     * @param status
     * @param vmOpensId
     * @param ipAddress
     * @return
     *     returns java.lang.Integer
     */
    @WebMethod(operationName = "ISAP_UpdateDatabase", action = "urn:ISAP_UpdateDatabase")
    @WebResult(targetNamespace = "http://core.isap.com")
    @RequestWrapper(localName = "ISAP_UpdateDatabase", targetNamespace = "http://core.isap.com", className = "com.isap.core.ISAPUpdateDatabase")
    @ResponseWrapper(localName = "ISAP_UpdateDatabaseResponse", targetNamespace = "http://core.isap.com", className = "com.isap.core.ISAPUpdateDatabaseResponse")
    public Integer isapUpdateDatabase(
        @WebParam(name = "vm_custom_id", targetNamespace = "http://core.isap.com")
        Integer vmCustomId,
        @WebParam(name = "vm_opens_id", targetNamespace = "http://core.isap.com")
        String vmOpensId,
        @WebParam(name = "ip_address", targetNamespace = "http://core.isap.com")
        String ipAddress,
        @WebParam(name = "status", targetNamespace = "http://core.isap.com")
        String status);

    /**
     * 
     * @param lof
     * @return
     *     returns com.isap.core.responses.xsd.ListOpenstackFlavorsResp
     */
    @WebMethod(operationName = "ListOpenstackFlavors", action = "urn:ListOpenstackFlavors")
    @WebResult(targetNamespace = "http://core.isap.com")
    @RequestWrapper(localName = "ListOpenstackFlavors", targetNamespace = "http://core.isap.com", className = "com.isap.core.ListOpenstackFlavors")
    @ResponseWrapper(localName = "ListOpenstackFlavorsResponse", targetNamespace = "http://core.isap.com", className = "com.isap.core.ListOpenstackFlavorsResponse")
    public ListOpenstackFlavorsResp listOpenstackFlavors(
        @WebParam(name = "lof", targetNamespace = "http://core.isap.com")
        ListOpenstackFlavorsReq lof);

    /**
     * 
     * @param goqr
     * @return
     *     returns com.isap.core.responses.xsd.GetOpenstackQuotaResp
     */
    @WebMethod(operationName = "GetOpenstackQuotaDetails", action = "urn:GetOpenstackQuotaDetails")
    @WebResult(targetNamespace = "http://core.isap.com")
    @RequestWrapper(localName = "GetOpenstackQuotaDetails", targetNamespace = "http://core.isap.com", className = "com.isap.core.GetOpenstackQuotaDetails")
    @ResponseWrapper(localName = "GetOpenstackQuotaDetailsResponse", targetNamespace = "http://core.isap.com", className = "com.isap.core.GetOpenstackQuotaDetailsResponse")
    public GetOpenstackQuotaResp getOpenstackQuotaDetails(
        @WebParam(name = "goqr", targetNamespace = "http://core.isap.com")
        GetOpenstackQuotaReq goqr);

    /**
     * 
     * @param req
     * @return
     *     returns com.isap.cloudmanager.responses.xsd.GetOpenstackFloatingIpResp
     */
    @WebMethod(action = "urn:listOpenstackFloatingIps")
    @WebResult(targetNamespace = "http://core.isap.com")
    @RequestWrapper(localName = "listOpenstackFloatingIps", targetNamespace = "http://core.isap.com", className = "com.isap.core.ListOpenstackFloatingIps")
    @ResponseWrapper(localName = "listOpenstackFloatingIpsResponse", targetNamespace = "http://core.isap.com", className = "com.isap.core.ListOpenstackFloatingIpsResponse")
    public GetOpenstackFloatingIpResp listOpenstackFloatingIps(
        @WebParam(name = "req", targetNamespace = "http://core.isap.com")
        OpenstackBasicReq req);

    /**
     * 
     * @param giids
     * @return
     *     returns com.isap.core.responses.xsd.GetIsapInstanceDetailsResp
     */
    @WebMethod(operationName = "GetIsapInstaceDetails", action = "urn:GetIsapInstaceDetails")
    @WebResult(targetNamespace = "http://core.isap.com")
    @RequestWrapper(localName = "GetIsapInstaceDetails", targetNamespace = "http://core.isap.com", className = "com.isap.core.GetIsapInstaceDetails")
    @ResponseWrapper(localName = "GetIsapInstaceDetailsResponse", targetNamespace = "http://core.isap.com", className = "com.isap.core.GetIsapInstaceDetailsResponse")
    public GetIsapInstanceDetailsResp getIsapInstaceDetails(
        @WebParam(name = "giids", targetNamespace = "http://core.isap.com")
        GetIsapinstanceDetailsReq giids);

    /**
     * 
     * @param cokreq
     * @return
     *     returns com.isap.core.responses.xsd.CreateOpenstackkeypairResp
     */
    @WebMethod(operationName = "CreateOpenstackKeypair", action = "urn:CreateOpenstackKeypair")
    @WebResult(targetNamespace = "http://core.isap.com")
    @RequestWrapper(localName = "CreateOpenstackKeypair", targetNamespace = "http://core.isap.com", className = "com.isap.core.CreateOpenstackKeypair")
    @ResponseWrapper(localName = "CreateOpenstackKeypairResponse", targetNamespace = "http://core.isap.com", className = "com.isap.core.CreateOpenstackKeypairResponse")
    public CreateOpenstackkeypairResp createOpenstackKeypair(
        @WebParam(name = "cokreq", targetNamespace = "http://core.isap.com")
        CreateOpenstackKeypairReq cokreq);

    /**
     * 
     * @param gofr
     * @return
     *     returns com.isap.cloudmanager.responses.xsd.GetOpenstackFlavorResp
     */
    @WebMethod(operationName = "GetOpenstackFlavorDetails", action = "urn:GetOpenstackFlavorDetails")
    @WebResult(targetNamespace = "http://core.isap.com")
    @RequestWrapper(localName = "GetOpenstackFlavorDetails", targetNamespace = "http://core.isap.com", className = "com.isap.core.GetOpenstackFlavorDetails")
    @ResponseWrapper(localName = "GetOpenstackFlavorDetailsResponse", targetNamespace = "http://core.isap.com", className = "com.isap.core.GetOpenstackFlavorDetailsResponse")
    public GetOpenstackFlavorResp getOpenstackFlavorDetails(
        @WebParam(name = "gofr", targetNamespace = "http://core.isap.com")
        GetOpenstackFlavorDetailsReq gofr);

    /**
     * 
     * @param goqr
     * @return
     *     returns com.isap.core.responses.xsd.GetOpenstackQuotaResp
     */
    @WebMethod(operationName = "GetOpenstackProjectUsage", action = "urn:GetOpenstackProjectUsage")
    @WebResult(targetNamespace = "http://core.isap.com")
    @RequestWrapper(localName = "GetOpenstackProjectUsage", targetNamespace = "http://core.isap.com", className = "com.isap.core.GetOpenstackProjectUsage")
    @ResponseWrapper(localName = "GetOpenstackProjectUsageResponse", targetNamespace = "http://core.isap.com", className = "com.isap.core.GetOpenstackProjectUsageResponse")
    public GetOpenstackQuotaResp getOpenstackProjectUsage(
        @WebParam(name = "goqr", targetNamespace = "http://core.isap.com")
        GetOpenstackQuotaReq goqr);

    /**
     * 
     * @param ghdr
     * @return
     *     returns com.isap.core.responses.xsd.GetOpenstackHypervisorDetailsResp
     */
    @WebMethod(operationName = "GetHypervisorDetails", action = "urn:GetHypervisorDetails")
    @WebResult(targetNamespace = "http://core.isap.com")
    @RequestWrapper(localName = "GetHypervisorDetails", targetNamespace = "http://core.isap.com", className = "com.isap.core.GetHypervisorDetails")
    @ResponseWrapper(localName = "GetHypervisorDetailsResponse", targetNamespace = "http://core.isap.com", className = "com.isap.core.GetHypervisorDetailsResponse")
    public GetOpenstackHypervisorDetailsResp getHypervisorDetails(
        @WebParam(name = "ghdr", targetNamespace = "http://core.isap.com")
        GetOpenstackHypervisorDetailsReq ghdr);

    /**
     * 
     * @param gicar
     * @return
     *     returns com.isap.core.responses.xsd.GetIsapCloudAuthenticationResponse
     */
    @WebMethod(operationName = "GetIsapCloudAuthentication", action = "urn:GetIsapCloudAuthentication")
    @WebResult(targetNamespace = "http://core.isap.com")
    @RequestWrapper(localName = "GetIsapCloudAuthentication", targetNamespace = "http://core.isap.com", className = "com.isap.core.GetIsapCloudAuthentication")
    @ResponseWrapper(localName = "GetIsapCloudAuthenticationResponse", targetNamespace = "http://core.isap.com", className = "com.isap.core.GetIsapCloudAuthenticationResponse")
    public GetIsapCloudAuthenticationResponse getIsapCloudAuthentication(
        @WebParam(name = "gicar", targetNamespace = "http://core.isap.com")
        GetIsapCloudAuthenticationRequest gicar);

    /**
     * 
     * @param lokr
     * @return
     *     returns com.isap.core.responses.xsd.ListOpenstackKeypairsResp
     */
    @WebMethod(operationName = "ListOpenstackKeypairs", action = "urn:ListOpenstackKeypairs")
    @WebResult(targetNamespace = "http://core.isap.com")
    @RequestWrapper(localName = "ListOpenstackKeypairs", targetNamespace = "http://core.isap.com", className = "com.isap.core.ListOpenstackKeypairs")
    @ResponseWrapper(localName = "ListOpenstackKeypairsResponse", targetNamespace = "http://core.isap.com", className = "com.isap.core.ListOpenstackKeypairsResponse")
    public ListOpenstackKeypairsResp listOpenstackKeypairs(
        @WebParam(name = "lokr", targetNamespace = "http://core.isap.com")
        ListOpenstackKeypairsReq lokr);

    /**
     * 
     * @param cotr
     * @return
     *     returns com.isap.core.responses.xsd.CreateOpenstackTenantResp
     */
    @WebMethod(operationName = "CreateOpenstackTenant", action = "urn:CreateOpenstackTenant")
    @WebResult(targetNamespace = "http://core.isap.com")
    @RequestWrapper(localName = "CreateOpenstackTenant", targetNamespace = "http://core.isap.com", className = "com.isap.core.CreateOpenstackTenant")
    @ResponseWrapper(localName = "CreateOpenstackTenantResponse", targetNamespace = "http://core.isap.com", className = "com.isap.core.CreateOpenstackTenantResponse")
    public CreateOpenstackTenantResp createOpenstackTenant(
        @WebParam(name = "cotr", targetNamespace = "http://core.isap.com")
        CreateOpenstacktenantReq cotr);

    /**
     * 
     * @param req
     * @return
     *     returns com.isap.cloudmanager.responses.xsd.GetOpenstackFloatingIpResp
     */
    @WebMethod(action = "urn:listOpenstackFloatingIpPools")
    @WebResult(targetNamespace = "http://core.isap.com")
    @RequestWrapper(localName = "listOpenstackFloatingIpPools", targetNamespace = "http://core.isap.com", className = "com.isap.core.ListOpenstackFloatingIpPools")
    @ResponseWrapper(localName = "listOpenstackFloatingIpPoolsResponse", targetNamespace = "http://core.isap.com", className = "com.isap.core.ListOpenstackFloatingIpPoolsResponse")
    public GetOpenstackFloatingIpResp listOpenstackFloatingIpPools(
        @WebParam(name = "req", targetNamespace = "http://core.isap.com")
        OpenstackBasicReq req);

    /**
     * 
     * @param tpir
     * @return
     *     returns java.lang.Integer
     */
    @WebMethod(operationName = "ISAPTerminateOpensInstance", action = "urn:ISAPTerminateOpensInstance")
    @WebResult(targetNamespace = "http://core.isap.com")
    @RequestWrapper(localName = "ISAPTerminateOpensInstance", targetNamespace = "http://core.isap.com", className = "com.isap.core.ISAPTerminateOpensInstance")
    @ResponseWrapper(localName = "ISAPTerminateOpensInstanceResponse", targetNamespace = "http://core.isap.com", className = "com.isap.core.ISAPTerminateOpensInstanceResponse")
    public Integer isapTerminateOpensInstance(
        @WebParam(name = "tpir", targetNamespace = "http://core.isap.com")
        TerminateOpensInstanceReq tpir);

}
