
package com.isap.core;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.isap.cloudmanager.requests.xsd.GetOpenstackFlavorDetailsReq;
import com.isap.cloudmanager.requests.xsd.GetOpenstackSecurityGroupDetailsReq;
import com.isap.cloudmanager.requests.xsd.ListOpenstackFlavorsReq;
import com.isap.cloudmanager.requests.xsd.ListOpenstackImagesReq;
import com.isap.cloudmanager.requests.xsd.ListOpenstackKeypairsReq;
import com.isap.cloudmanager.requests.xsd.ListOpenstackNetworksReq;
import com.isap.cloudmanager.requests.xsd.ListOpenstackSecurityGroupsReq;
import com.isap.cloudmanager.responses.xsd.GetOpenstackFlavorResp;
import com.isap.core.requests.xsd.GetIsapCloudAuthenticationRequest;
import com.isap.core.requests.xsd.GetIsapLaunchInstanceReq;
import com.isap.core.requests.xsd.GetIsapinstanceDetailsReq;
import com.isap.core.responses.xsd.GetIsapCloudAuthenticationResponse;
import com.isap.core.responses.xsd.GetIsapInstanceDetailsResp;
import com.isap.core.responses.xsd.GetIsapLaunchInstanceResp;
import com.isap.core.responses.xsd.GetOpenstackSecurityGroupDetailsResp;
import com.isap.core.responses.xsd.ListOpenstackFlavors;
import com.isap.core.responses.xsd.ListOpenstackImagesResp;
import com.isap.core.responses.xsd.ListOpenstackKeypairsResp;
import com.isap.core.responses.xsd.ListOpenstackNetworksResp;
import com.isap.core.responses.xsd.ListOpenstackSecurityGroupsResp;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IsapCoreWebservicesPortType", targetNamespace = "http://core.isap.com")
@XmlSeeAlso({
    com.isap.cloudmanager.requests.xsd.ObjectFactory.class,
    com.isap.cloudmanager.responses.xsd.ObjectFactory.class,
    com.isap.core.ObjectFactory.class,
    com.isap.core.requests.xsd.ObjectFactory.class,
    com.isap.core.responses.xsd.ObjectFactory.class
})
public interface IsapCoreWebservicesPortType {


    /**
     * 
     * @param gosgr
     * @return
     *     returns com.isap.core.responses.xsd.GetOpenstackSecurityGroupDetailsResp
     */
    @WebMethod(operationName = "GetOpenstackSecurityGroupDetails", action = "urn:GetOpenstackSecurityGroupDetails")
    @WebResult(targetNamespace = "http://core.isap.com")
    @RequestWrapper(localName = "GetOpenstackSecurityGroupDetails", targetNamespace = "http://core.isap.com", className = "com.isap.core.GetOpenstackSecurityGroupDetails")
    @ResponseWrapper(localName = "GetOpenstackSecurityGroupDetailsResponse", targetNamespace = "http://core.isap.com", className = "com.isap.core.GetOpenstackSecurityGroupDetailsResponse")
    public GetOpenstackSecurityGroupDetailsResp getOpenstackSecurityGroupDetails(
        @WebParam(name = "gosgr", targetNamespace = "http://core.isap.com")
        GetOpenstackSecurityGroupDetailsReq gosgr);

    /**
     * 
     * @param losgr
     * @return
     *     returns com.isap.core.responses.xsd.ListOpenstackSecurityGroupsResp
     */
    @WebMethod(operationName = "ListOpenstackSecurityGroups", action = "urn:ListOpenstackSecurityGroups")
    @WebResult(targetNamespace = "http://core.isap.com")
    @RequestWrapper(localName = "ListOpenstackSecurityGroups", targetNamespace = "http://core.isap.com", className = "com.isap.core.ListOpenstackSecurityGroups")
    @ResponseWrapper(localName = "ListOpenstackSecurityGroupsResponse", targetNamespace = "http://core.isap.com", className = "com.isap.core.ListOpenstackSecurityGroupsResponse")
    public ListOpenstackSecurityGroupsResp listOpenstackSecurityGroups(
        @WebParam(name = "losgr", targetNamespace = "http://core.isap.com")
        ListOpenstackSecurityGroupsReq losgr);

    /**
     * 
     * @param gilir
     * @return
     *     returns com.isap.core.responses.xsd.GetIsapLaunchInstanceResp
     */
    @WebMethod(operationName = "GetIsapLaunchinstance", action = "urn:GetIsapLaunchinstance")
    @WebResult(targetNamespace = "http://core.isap.com")
    @RequestWrapper(localName = "GetIsapLaunchinstance", targetNamespace = "http://core.isap.com", className = "com.isap.core.GetIsapLaunchinstance")
    @ResponseWrapper(localName = "GetIsapLaunchinstanceResponse", targetNamespace = "http://core.isap.com", className = "com.isap.core.GetIsapLaunchinstanceResponse")
    public GetIsapLaunchInstanceResp getIsapLaunchinstance(
        @WebParam(name = "gilir", targetNamespace = "http://core.isap.com")
        GetIsapLaunchInstanceReq gilir);

    /**
     * 
     * @param lonr
     * @return
     *     returns com.isap.core.responses.xsd.ListOpenstackNetworksResp
     */
    @WebMethod(operationName = "ListOpenstackNetworks", action = "urn:ListOpenstackNetworks")
    @WebResult(targetNamespace = "http://core.isap.com")
    @RequestWrapper(localName = "ListOpenstackNetworks", targetNamespace = "http://core.isap.com", className = "com.isap.core.ListOpenstackNetworks")
    @ResponseWrapper(localName = "ListOpenstackNetworksResponse", targetNamespace = "http://core.isap.com", className = "com.isap.core.ListOpenstackNetworksResponse")
    public ListOpenstackNetworksResp listOpenstackNetworks(
        @WebParam(name = "lonr", targetNamespace = "http://core.isap.com")
        ListOpenstackNetworksReq lonr);

    /**
     * 
     * @param loir
     * @return
     *     returns com.isap.core.responses.xsd.ListOpenstackImagesResp
     */
    @WebMethod(operationName = "ListOpenstackImages", action = "urn:ListOpenstackImages")
    @WebResult(targetNamespace = "http://core.isap.com")
    @RequestWrapper(localName = "ListOpenstackImages", targetNamespace = "http://core.isap.com", className = "com.isap.core.ListOpenstackImages")
    @ResponseWrapper(localName = "ListOpenstackImagesResponse", targetNamespace = "http://core.isap.com", className = "com.isap.core.ListOpenstackImagesResponse")
    public ListOpenstackImagesResp listOpenstackImages(
        @WebParam(name = "loir", targetNamespace = "http://core.isap.com")
        ListOpenstackImagesReq loir);

    /**
     * 
     * @param vmCustomId
     * @param status
     * @param ipAddress
     * @return
     *     returns java.lang.Integer
     */
    @WebMethod(operationName = "ISAP_UpdateDatabase", action = "urn:ISAP_UpdateDatabase")
    @WebResult(targetNamespace = "http://core.isap.com")
    @RequestWrapper(localName = "ISAP_UpdateDatabase", targetNamespace = "http://core.isap.com", className = "com.isap.core.ISAPUpdateDatabase")
    @ResponseWrapper(localName = "ISAP_UpdateDatabaseResponse", targetNamespace = "http://core.isap.com", className = "com.isap.core.ISAPUpdateDatabaseResponse")
    public Integer isapUpdateDatabase(
        @WebParam(name = "vm_custom_id", targetNamespace = "http://core.isap.com")
        Integer vmCustomId,
        @WebParam(name = "ip_address", targetNamespace = "http://core.isap.com")
        String ipAddress,
        @WebParam(name = "status", targetNamespace = "http://core.isap.com")
        String status);

    /**
     * 
     * @param lof
     * @return
     *     returns com.isap.core.responses.xsd.ListOpenstackFlavors
     */
    @WebMethod(operationName = "ListOpenstackFlavors", action = "urn:ListOpenstackFlavors")
    @WebResult(targetNamespace = "http://core.isap.com")
    @RequestWrapper(localName = "ListOpenstackFlavors", targetNamespace = "http://core.isap.com", className = "com.isap.core.ListOpenstackFlavors")
    @ResponseWrapper(localName = "ListOpenstackFlavorsResponse", targetNamespace = "http://core.isap.com", className = "com.isap.core.ListOpenstackFlavorsResponse")
    public ListOpenstackFlavors listOpenstackFlavors(
        @WebParam(name = "lof", targetNamespace = "http://core.isap.com")
        ListOpenstackFlavorsReq lof);

    /**
     * 
     * @param giids
     * @return
     *     returns com.isap.core.responses.xsd.GetIsapInstanceDetailsResp
     */
    @WebMethod(operationName = "GetIsapInstaceDetails", action = "urn:GetIsapInstaceDetails")
    @WebResult(targetNamespace = "http://core.isap.com")
    @RequestWrapper(localName = "GetIsapInstaceDetails", targetNamespace = "http://core.isap.com", className = "com.isap.core.GetIsapInstaceDetails")
    @ResponseWrapper(localName = "GetIsapInstaceDetailsResponse", targetNamespace = "http://core.isap.com", className = "com.isap.core.GetIsapInstaceDetailsResponse")
    public GetIsapInstanceDetailsResp getIsapInstaceDetails(
        @WebParam(name = "giids", targetNamespace = "http://core.isap.com")
        GetIsapinstanceDetailsReq giids);

    /**
     * 
     * @param gofr
     * @return
     *     returns com.isap.cloudmanager.responses.xsd.GetOpenstackFlavorResp
     */
    @WebMethod(operationName = "GetOpenstackFlavorDetails", action = "urn:GetOpenstackFlavorDetails")
    @WebResult(targetNamespace = "http://core.isap.com")
    @RequestWrapper(localName = "GetOpenstackFlavorDetails", targetNamespace = "http://core.isap.com", className = "com.isap.core.GetOpenstackFlavorDetails")
    @ResponseWrapper(localName = "GetOpenstackFlavorDetailsResponse", targetNamespace = "http://core.isap.com", className = "com.isap.core.GetOpenstackFlavorDetailsResponse")
    public GetOpenstackFlavorResp getOpenstackFlavorDetails(
        @WebParam(name = "gofr", targetNamespace = "http://core.isap.com")
        GetOpenstackFlavorDetailsReq gofr);

    /**
     * 
     * @param gicar
     * @return
     *     returns com.isap.core.responses.xsd.GetIsapCloudAuthenticationResponse
     */
    @WebMethod(operationName = "GetIsapCloudAuthentication", action = "urn:GetIsapCloudAuthentication")
    @WebResult(targetNamespace = "http://core.isap.com")
    @RequestWrapper(localName = "GetIsapCloudAuthentication", targetNamespace = "http://core.isap.com", className = "com.isap.core.GetIsapCloudAuthentication")
    @ResponseWrapper(localName = "GetIsapCloudAuthenticationResponse", targetNamespace = "http://core.isap.com", className = "com.isap.core.GetIsapCloudAuthenticationResponse")
    public GetIsapCloudAuthenticationResponse getIsapCloudAuthentication(
        @WebParam(name = "gicar", targetNamespace = "http://core.isap.com")
        GetIsapCloudAuthenticationRequest gicar);

    /**
     * 
     * @param lokr
     * @return
     *     returns com.isap.core.responses.xsd.ListOpenstackKeypairsResp
     */
    @WebMethod(operationName = "ListOpenstackKeypairs", action = "urn:ListOpenstackKeypairs")
    @WebResult(targetNamespace = "http://core.isap.com")
    @RequestWrapper(localName = "ListOpenstackKeypairs", targetNamespace = "http://core.isap.com", className = "com.isap.core.ListOpenstackKeypairs")
    @ResponseWrapper(localName = "ListOpenstackKeypairsResponse", targetNamespace = "http://core.isap.com", className = "com.isap.core.ListOpenstackKeypairsResponse")
    public ListOpenstackKeypairsResp listOpenstackKeypairs(
        @WebParam(name = "lokr", targetNamespace = "http://core.isap.com")
        ListOpenstackKeypairsReq lokr);

}
